### PR TITLE
HttpResponse mimetype attribute was deprecated since Django 1.5

### PR DESCRIPTION
**Pull request by muhammedabad**
Fix bug encountered in django >= 1.5

### CODE REVIEW

**Comment by plumdog** [comment]
Hi. Thanks for this fix!

I'd rather the HTML wasn't repeated, so maybe
```python
# sort out `**kwargs` here based on `django.version`, then:
response = HttpResponse(
    """<html><title>Auth required</title><body>
    <h1>Authorization Required</h1></body></html>""",
    **kwargs
)
```

**Comment by muhammedabad** [comment]
Fair enough - I've updated the code to handle this. I've also gotten rid of the `has_key()` method, which is also deprecated.

**Comment by muhammedabad** [comment]
Last commit (8b035f9) ensures the headers are set correctly - was previously being defined as type `set`

**Comment by plumdog** [comment]
All looks good to me. :+1: Could I ask you to squash your commits into one? Then I'll merge.

**Comment by muhammedabad** [comment]
14df86e should be right, let me know.

**Comment by plumdog** [comment]
You've got the squashed commit, but also a merge of the individual commits. I think you'll want to
`git reset --hard 14df86e` to reset your branch to contain just that commit, then do a `git push -f`. Then there should be just one commit listed in the PR, with the squashed changes.

**Comment by muhammedabad** [comment]
Done

**Comment by plumdog** [comment]
Brill, thanks!

**Pull request merged**
